Net/ThemeName "Flat-Remix-GTK-White-Darkest"
Net/IconThemeName "Reversal-black"
Gtk/CursorThemeName "Vimix-white-cursors"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintmedium"
Xft/RGBA "rgb"
