# Thunar - gerenciador de arquivos
windowrulev2 = rounding 10, class:(thunar)
windowrulev2 = opacity 0.90, class:(thunar)

# Pavucontrol - Controle de volume
windowrulev2 = rounding 10, class:(pavucontrol)
windowrulev2 = size 800 600, class:(pavucontrol)
windowrulev2 = center, class:(pavucontrol)
windowrulev2 = nofocus, class:(pavucontrol) 
windowrulev2 = opacity 0.85, class:(pavucontrol)

# Blueman - Controle de bluetooth
windowrulev2 = float, class:(blueman-manager)
windowrulev2 = rounding 10, class:(blueman-manager)
windowrulev2 = size 900 550, class:(blueman-manager)
windowrulev2 = center, class:(blueman-manager)
windowrulev2 = opacity 0.85, class:(blueman-manager)

# Regras xwayland
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# Comportamentos para abertura de janelas
dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = true
    smart_resizing = true
}

master {
    new_status = master
}


misc {
    vfr = true # pode ser necessário desativar o uso de acelaração de GPU do navegador
    vrr = false
    disable_hyprland_logo = true
    disable_splash_rendering = false
    mouse_move_enables_dpms = true
    enable_swallow = true
    disable_autoreload = false
    focus_on_activate = true
}
