[general]
temp-day=6500
temp-night=3600
fade=1
adjustment-method=wayland
location-provider=manual
brightness-day=1.0
brightness-night=0.9
transition=1

[manual]
# Coordenadas para definir o horário de dia e noite
lat=22.7327
lon=-48.5726