$font = JetBrainsMono Nerd Font Propo

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/joannes/Pictures/Wallpapers/9.png
}
    
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 1
    dots_size = 0.2 
    dots_spacing = 0.2
    dots_center = true

    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(ffffffcc) rgba(000000cc) 45deg
    check_color = rgba(ffffffcc) rgba(000000cc) 120deg
    fail_color = rgba(000000cc) rgba(ffffffcc) 40deg

    font_color = rgba(255, 255, 255, 1)
    fade_on_empty = true
    rounding = 8

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL
    position = 0, -250
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_family = $font
    font_size = 42
    font_color = rgba(255, 255, 255, 1)

    position = 0, 250
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 26
    font_family = $font
    font_color = rgba(255, 255, 255, 1)
    position = 0, -850
    halign = center
    valign = top
}

# USERNAME
label {
    monitor =
    text = Welcome $USER!
    font_family = $font
    font_color = rgba(255, 255, 255, 1)
    font_size = 36
    position = 0, -150
    halign = center
    valign = top
}
