exec-once = bash ~/.config/hypr/scripts/autostart.sh
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/windowrulev2.conf
source = ~/.config/hypr/conf/bind.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/personalization.conf
