background_opacity 0.85
font_family JetBrainsMono Nerd Font
font_size 12.0
line_height 1.1
letter_spacing 0.0

foreground #FFFFFF
background #000000

cursor #FFFFFF
selection_background #222222
selection_foreground #FFFFFF

cursor_beam_width 2
cursor_thickness 2
cursor_blink_interval 0.5

window_padding_width 5
allow_bold yes
scrollback_lines 10000
mouse_hide_wait 2.0
enable_ligatures yes
italic_underline yes
detect_urls yes
url_color #CCCCCC
url_style curly
